### ISSUE TITLE
django-jsonfield-backport 1.0.1 requires Django>2.2, but you'll have django 2.2 which is incompatible.

### ISSUE THREAD

**Issue by dfrank8** [laymonage/django-jsonfield-backport#18]
I'm currently using django 2.2 and faced the bug described here: https://code.djangoproject.com/ticket/30335

This led me to this backport. I'm confused though, every time I try to install it  `pip install django-jsonfield-backport`, it forces an upgrade to django 3.1, which is what I'm trying to avoid. If I force django back to 2.2, I get the error from the title `django-jsonfield-backport 1.0.1 requires Django>2.2, but you'll have django 2.2 which is incompatible.`.

The docs say:

Requirements
This package supports and is tested against the latest patch versions of:

**Django: 2.2, 3.0, 3.1**

Am I missing something with the installation? Or am I misunderstanding the purpose of this package?

Thanks

**Comment by laymonage** [comment]
Hi @dfrank8, Are you using the latest patch version of Django 2.2, i.e. Django 2.2.16? This package only officially supports the latest patch versions, but I think it should still work on 2.2.x. However, with the version requirement specified as `>2.2`, I think you need at least 2.2.1 (not 2.2.0), unless I misunderstood how pip's version specifier works.

Then again, if you're using 2.2, you *should* update to the latest patch version every time. Django 2.2.0 is already years old and has security vulnerabilities.

**Comment by laymonage** [comment]
This is fixed as of [v1.0.2](https://github.com/laymonage/django-jsonfield-backport/releases/tag/v1.0.2). Thanks for the report!
