### ISSUE TITLE
DatabaseFeatures error with SQLite

### ISSUE THREAD

**Issue by nick-falco** [laymonage/django-jsonfield-backport#23]
I'm trying to use the `django-jsonfield-backport` package with Sqlite3 version 3.4.0 and Django version 2.2.17. I'm running macOS Catalina which from my understanding comes preinstalled with the SQLite JSON1 extension. 

I am able to write json data to the db without any issues, however I am encountering an error when querying the db:

```
  File "/Users/nick/Development/workspace/django-jsonfield-backport/src/django_jsonfield_backport/models.py", line 112, in from_db_value
    if connection.features.has_native_json_field and self.decoder is None:
AttributeError: 'DatabaseFeatures' object has no attribute 'has_native_json_field'
```

I cloned the latest version of this project in development mode. Upon debugging it appears that the `DatabaseFeatures` object only contains a reference to the connection. On line 111 in the `from_db_value` method of models.py I print the connection.features object. As you can see, it doesn't contain all of the attributes that are expected.

```
>>>print(connection.features.__dict__)
{'connection': <django.db.backends.sqlite3.base.DatabaseWrapper object at 0x10b4cc128>}
```

I believe the problem is that Django is using the default DatabaseFeatures backend for SQLite. Printing the features object in the `from_db_value` method returns the following reference:

```
>>>print(connection.features)
<django.db.backends.sqlite3.features.DatabaseFeatures>
```

Any idea how to fix this?

**Comment by laymonage** [comment]
Hi @nick-falco,

Have you added this package to `INSTALLED_APPS`? See #14 for more details.
